### ISSUE TITLE
Make clients independent of test chain

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/spacewalk#71]
Currently the clients refer to the testchain (they have a dependency to `spacewalk_runtime`). This is meant to use the definition of `AccountId`, `Address` and `Balance` of the testchain. However, this makes the client only usable for Substrate chains that use the same configuration parameters as the testchain – which is not true.

Another parameter that is hardcoded is what kind of extra information the pallet-transaction-payment requires in the extrinsic of the chain. This information is usually just the tip but the type of the tip also differs between chains: it can be a tip in the native currency and will just require the tip amount or it can be a tip expressed as a multicurrency that requires the tip amount and tip asset.

We should understand what typical configuration parameters are (research Polkadot and Kusama parachains) and come up with a list of settings for each of the parameters. I guess that this is
* `AccountId`: seems to be `sp_core::crypto::AccountId32` for most chains
* `Address`: seems to be either `AccountId` or `sp_runtime::MultiAddress<AccountId, ()>`
* `Balance`: seems to be `u128` for most chains
* tip format: either `PlainTip` (native asset) or `AssetTip` (specifying an asset)

Once we know what kind of parameters we need, we should find a way for users of the vault to specify the proper settings for their own chain. This should most likely happen at compile time. Maybe it can happen through cargo features.

### Tasks
  
* [ ] research typical settings for the 4 parameters
* [ ] find a way that allows to specify these parameters at compile time without requiring to touch the code
* [ ] implement
* [ ] add to README
